### PR TITLE
Proposal for better Exceptions

### PR DESCRIPTION
**Pull request by sekjun9878**
Proposal for better exceptions.

The new exception system will allow extending and derivative software to easily build cases on different exceptions without having to parse the string output of an exceptions.

This change is backwards compatible: applications can still catch for the SourceQueryException, however they can also choose to be more specific and catch specific exceptions instead.

Not that the SourceQueryException has been turned into an abstract class so it cannot be used directly.

### CODE REVIEW

**Comment by xPaw** [comment]
Looks fine to me. However your previous pull request already added `.gitignore` so it conflicts. Could you rebase it?

**Comment by sekjun9878** [comment]
Will do!

**Comment by sekjun9878** [comment]
@xPaw Conflict solved!

**Comment by xPaw** [comment]
Hmm, your commit adds same stuff that appeared in previous commits; could you please do a clean force push, so that it doesn't mess with the history?

**Comment by sekjun9878** [comment]
@xPaw What do you mean? I merged my branch with your upstream/master so the only changes now should be the actual exception changes?

**Comment by xPaw** [comment]
You did merge it, but that created an additional commit with same changes that are already in master branch.

This should help: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by sekjun9878** [comment]
Fixed

**Comment by xPaw** [comment]
Thanks!

**Pull request merged**
